services:
  lb:
    image: haproxy:2.8
    ports:
      - "3100:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - app-network
    depends_on:
      - auth-service
      - usuarios-service
      - menu-inventario-service
      - pagos-service
      - comandas-service
    restart: unless-stopped

  auth-service:
    build: ./auth
    command: npm run dev
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=auth-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - DB_PORT=5432
      - JWT_SECRET=b6e70d520b3ce38f4e30741efce06a0583a50c71135af30a843676f352c56a48cb8b92faca76bebe9bd8d35f2e3c4f6039f6a259046582986acdbbbc457677e1
    depends_on:
      - auth-db

  usuarios-service:
    build: ./usuarios
    command: npm run dev
    ports:
      - "3002:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=usuarios-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=usuarios_db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - usuarios-db
      - auth-service

  menu-inventario-service:
    build: ./menu_inventario
    command: npm run dev
    ports:
      - "3003:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=menu_inventario-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=menu_inventario_db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - menu_inventario-db
      - auth-service

  pagos-service:
    build: ./pagos
    command: npm run dev
    ports:
      - "3004:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=pagos-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=pagos_db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:3000
    depends_on:
      - pagos-db
      - auth-service

  comandas-service:
    build: ./comandas
    command: npm run dev
    ports:
      - "3005:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=comandas-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=comandas_db
      - DB_PORT=5432
      - AUTH_SERVICE_URL=http://auth-service:3000
      - PAGOS_SERVICE_URL=http://pagos-service:3000
      - USUARIOS_SERVICE_URL=http://usuarios-service:3000
      - MENU_INVENTARIO_SERVICE_URL=http://menu-inventario-service:3000
    depends_on:
      - comandas-db
      - auth-service
      - pagos-service
      - usuarios-service
      - menu-inventario-service

  # Databases
  auth-db:
    image: postgres:13
    ports:
      - "5431:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - ./auth/db-init:/docker-entrypoint-initdb.d

  usuarios-db:
    image: postgres:13
    ports:
      - "5434:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=usuarios_db
    volumes:
      - ./usuarios/db-init:/docker-entrypoint-initdb.d

  menu_inventario-db:
    image: postgres:13
    ports:
      - "5435:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=menu_inventario_db
    volumes:
      - ./menu_inventario/db-init:/docker-entrypoint-initdb.d

  pagos-db:
    image: postgres:13
    ports:
      - "5437:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pagos_db
    volumes:
      - ./pagos/db-init:/docker-entrypoint-initdb.d

  comandas-db:
    image: postgres:13
    ports:
      - "5438:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comandas_db
    volumes:
      - ./comandas/db-init:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge